services:
  postgres:
    image: postgis/postgis:16-3.4 # Use the official PostGIS image
    container_name: parkease_db
    environment:
      POSTGRES_USER: parkease
      POSTGRES_PASSWORD: parkease
      POSTGRES_DB: parkease_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U parkease"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
